version: "3.8"

services:
  web:
    build:
      context: .
    container_name: Esportify
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: mariadb:11.7.2
    container_name: bdd-java-local
    restart: unless-stopped
    environment:
      MARIADB_USERNAME: root
      MARIADB_ROOT_PASSWORD: supermotdepasse
      MARIADB_DATABASE: esports_db
    ports:
      - "3307:3306"
    volumes:
      - ./esports_db.sql:/docker-entrypoint-initdb.d/esports_db.sql
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_DB: esports_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: supermotdepasse
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
  pg_data: